version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Starting Build..."
      - python app1.py
      - echo "Build Successful"

artifacts:
  files:
    - '**/*'
